<?php

/**
 * @copyright   ©2025 Maatify.dev
 * @Library     maatify/security-guard
 * @Project     maatify:security-guard
 * @author      Mohamed Abdulalim (megyptm) <mohamed@maatify.dev>
 * @since       2025-12-11 09:10
 * @see         https://www.maatify.dev Maatify.dev
 * @link        https://github.com/Maatify/security-guard view Project on GitHub
 * @note        Distributed in the hope that it will be useful - WITHOUT WARRANTY.
 */

declare(strict_types=1);


/**
 * Phase 5 – Slim Example #8
 * EVENT DISPATCHING (STRICT)
 *
 * Demonstrates:
 *  - Attaching a custom event dispatcher to SecurityGuardService
 *  - Receiving SecurityEventDTO objects generated by Phase 5 flows
 *  - Triggering events from: failures, auto-block, manual block, cleanup
 */


use Maatify\SecurityGuard\DTO\SecurityEventDTO;
use Maatify\SecurityGuard\Service\SecurityGuardService;
use Maatify\SecurityGuard\DTO\LoginAttemptDTO;
use Maatify\SecurityGuard\DTO\SecurityBlockDTO;
use Maatify\SecurityGuard\Event\Contracts\EventDispatcherInterface;
use Maatify\SecurityGuard\Enums\BlockTypeEnum;

// -------------------------------------------------------------
// 1) Slim DI container + bootstrap
// -------------------------------------------------------------
$app = require __DIR__ . '/bootstrap.php';

/** @var SecurityGuardService $guard */
$guard = $app->getContainer()->get(SecurityGuardService::class);

// -------------------------------------------------------------
// 2) Create a very simple dispatcher (STRICT PSR-style)
// -------------------------------------------------------------
class SimpleSlimDispatcher implements EventDispatcherInterface
{
    public function dispatch(SecurityEventDTO $event): void
    {
        echo "\n=== Security Event Received ===\n";
        echo "Action:      {$event->action->value}\n";
        echo "IP:          {$event->ip}\n";
        echo "Subject:     {$event->subject}\n";
        echo "Platform:    {$event->platform->value}\n";
        echo "Timestamp:   {$event->timestamp}\n";

        if (!empty($event->context)) {
            echo "Context:     " . json_encode($event->context, JSON_PRETTY_PRINT) . "\n";
        }

        echo "===============================\n";
    }
}

$guard->setEventDispatcher(new SimpleSlimDispatcher());

echo "\n=== Slim Example #8 — EVENTS (STRICT) ===\n\n";

// Load config
$config = $guard->getConfig();
$window = $config->windowSeconds();

$ip = "203.55.10.8";
$subject = "events_demo_user";

// -------------------------------------------------------------
// 3) FAILURE → should dispatch a LOGIN_FAILURE event
// -------------------------------------------------------------
echo "→ Triggering failure event...\n";

$attemptFail = LoginAttemptDTO::now(
    ip        : $ip,
    subject   : $subject,
    resetAfter: $window,
    userAgent : "CLI",
    context   : ['event' => 'login_failure']
);

$guard->handleAttempt($attemptFail, false);

// -------------------------------------------------------------
// 4) MANUAL BLOCK → should dispatch BLOCK_CREATED event
// -------------------------------------------------------------
echo "\n→ Triggering block event...\n";

$block = new SecurityBlockDTO(
    ip       : $ip,
    subject  : $subject,
    type     : BlockTypeEnum::MANUAL,
    expiresAt: time() + 300,
    createdAt: time()
);

$guard->block($block);

// -------------------------------------------------------------
// 5) Cleanup → should dispatch CLEANUP event
// -------------------------------------------------------------
echo "\n→ Triggering cleanup event...\n";

$guard->cleanup();

echo "\n=== END OF EVENTS EXAMPLE ===\n\n";
